# PATH
TRAIN_PATH: "/opt/ml/dataset/train/remove_duplicated_train.csv"
DEV_PATH: "/opt/ml/dataset/train/remove_duplicated_train.csv"
SPLIT_TRAIN_PATH: "/opt/ml/dataset/save_split_dataset/train.csv"
SPLIT_DEV_PATH: "/opt/ml/dataset/save_split_dataset/dev.csv"
TEST_PATH: "/opt/ml/dataset/test/test_data.csv"

OUTPUT_DIR: "./results/roberta_large_mlm_er_lr5.0e-5_batch32"
LOGGING_DIR: "./logs"
MODEL_SAVE_DIR: "/opt/ml/results/roberta_large_mlm_er_lr5.0e-5_batch32/checkpoint-2500"

# MODEL (확인 필수)
MODEL_NAME: "klue/roberta-large"
MODEL_PATH: "/opt/ml/best_model/pretrain/roberta_large_mlm_lr5.0e-5_batch64"
TOTAL_SAVE_MODEL: 5

# LOSS (확인 필수)
LOSS_FN: 'label_smoothing' # 'base', 'focal', 'label_smoothing'

# HYPER PARAMETER (확인 필수)
MAX_EPOCH: 3
LR: 2.0e-5 # Example Format : 5.0e-5 / 5.e-5 / 5.E-5
BATCH_SIZE: 64
WARMUP_STEP: 400
RATIO: 0.15 # Train Validation Split ratio
WEIGHT_DECAY: 0.1

# LOG
SAVING_STEP: 500
LOGGING_STEP: 500
EVAL_STEP: 500
STRATEGY: "steps" ### 추가부분

# WANDB (확인 필수)
WANDB_PROJECT: "merge_test"
WANDB_NAME: "test"

# WANDB SWEEP (확인 필수 및 양식 확인(들여쓰기))
SWEEP_AVAILABLE: 0 # SWEEP을 사용할 것인지 (1 : 사용, 0 : 미사용)
SWEEP_COUNT: 8 # SWEEP 실행 횟수
SWEEP_CONFIGURATION: # SWEEP 세부 내용 설정
  method: 'grid'
  name: 'epoch and lr tuning'
  metric:
    goal: 'maximize'
    name: 'eval/micro f1 score'
  parameters:
    batch_size:
      values:
      - 32
    epochs:
      values:
      - 3
      - 4
      - 6
      - 8
    warmup_steps:
      values:
      - 500
      - 1000
    lr:
      values:
      - 5.0e-5

# Custom Model (확인 필수)
MODEL_TYPE: 'entity_punct' # 'base', 'entity_special', 'entity_punct'
DO_SEQUENTIALBERTMODEL: 1 # SequentialBertModel 사용 여부 (0 : 미사용, 1 : 사용)
DISCRIP: 0
PRE_TRAIN : 'MLM' # None, MLM, NER, MLM_NER
